INSTALL_KOKKOS_DIR=$INSTALL_DIR/kokkos

cmake $KOKKOS_DIR -B $BUILD_DIR/kokkos  -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR/kokkos -DCMAKE_BUILD_TYPE=Release -DKokkos_ENABLE_CUDA=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON

cd build/kokkos

make -j $NB_MAKE_PROCS
make install
